//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int AdminID { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciSifresi { get; set; }
        public string Yetki { get; set; }
    }
}
