//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caris()
        {
            this.SatisHarekets = new HashSet<SatisHarekets>();
        }
    
        public int CariID { get; set; }
        public string CariAdi { get; set; }
        public string CariSoyadi { get; set; }
        public string CariSehir { get; set; }
        public string CariMaili { get; set; }
        public bool CariDurumu { get; set; }
        public string CariSifresi { get; set; }
        public string CariGorseli { get; set; }
        public string Adres { get; set; }
        public string CariTelefon { get; set; }
        public string EgitimBilgisi { get; set; }
        public string YetenekBilgisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisHarekets> SatisHarekets { get; set; }
    }
}
