//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faturas()
        {
            this.FaturaKalems = new HashSet<FaturaKalems>();
        }
    
        public int FaturaID { get; set; }
        public string FaturaSeriNo { get; set; }
        public string FaturaSiraNo { get; set; }
        public System.DateTime FaturaTarih { get; set; }
        public string FaturaSaat { get; set; }
        public string FaturaTeslimEden { get; set; }
        public string FaturaTeslimAlan { get; set; }
        public string FaturaVergiDairesi { get; set; }
        public decimal ToplamTutar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaKalems> FaturaKalems { get; set; }
    }
}
