//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giders
    {
        public int GiderID { get; set; }
        public string GiderAciklama { get; set; }
        public System.DateTime GiderTarih { get; set; }
        public decimal GiderTutar { get; set; }
    }
}
