//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajs
    {
        public int MesajID { get; set; }
        public string Alici { get; set; }
        public string Gonderici { get; set; }
        public string Konu { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Icerik { get; set; }
    }
}
