//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcOnlineTicariOtomasyonEntities1 : DbContext
    {
        public MvcOnlineTicariOtomasyonEntities1()
            : base("name=MvcOnlineTicariOtomasyonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Caris> Caris { get; set; }
        public virtual DbSet<Departmen> Departmen { get; set; }
        public virtual DbSet<Detays> Detays { get; set; }
        public virtual DbSet<FaturaKalems> FaturaKalems { get; set; }
        public virtual DbSet<Faturas> Faturas { get; set; }
        public virtual DbSet<Giders> Giders { get; set; }
        public virtual DbSet<KargoDetays> KargoDetays { get; set; }
        public virtual DbSet<KargoTakips> KargoTakips { get; set; }
        public virtual DbSet<Kategoris> Kategoris { get; set; }
        public virtual DbSet<Mesajs> Mesajs { get; set; }
        public virtual DbSet<Personels> Personels { get; set; }
        public virtual DbSet<SatisHarekets> SatisHarekets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uruns> Uruns { get; set; }
        public virtual DbSet<YapilacakListesis> YapilacakListesis { get; set; }
    }
}
