//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisHarekets
    {
        public int SatisHareketID { get; set; }
        public System.DateTime SatisHareketTarihi { get; set; }
        public int SatisHareketAdedi { get; set; }
        public decimal SatisHareketFiyati { get; set; }
        public decimal SatisHareketToplamTutari { get; set; }
        public int Cariid { get; set; }
        public int Personelid { get; set; }
        public int Urunid { get; set; }
    
        public virtual Caris Caris { get; set; }
        public virtual Personels Personels { get; set; }
        public virtual Uruns Uruns { get; set; }
    }
}
