//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Islemleri_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uruns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uruns()
        {
            this.SatisHarekets = new HashSet<SatisHarekets>();
        }
    
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string UrunMarka { get; set; }
        public short UrunStok { get; set; }
        public decimal UrunAlisFiyati { get; set; }
        public decimal UrunSatisFiyati { get; set; }
        public bool UrunDurumu { get; set; }
        public string UrunGorseli { get; set; }
        public int Kategoriid { get; set; }
    
        public virtual Kategoris Kategoris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisHarekets> SatisHarekets { get; set; }
    }
}
